export const cards = [
'yī', 'one',
'èr', 'two',
'sān', 'three',
'sì', 'four',
'wǔ', 'five',
'liù', 'six',
'qī', 'seven',
'bā', 'eight',
'jiǔ', 'nine',
'shí', 'ten',
'rì', 'sun',
'yuè', 'moon, month',
'rén', 'person',
'dà', 'big',
'tóu', 'head, first',
'tài', 'too, the greatest',
'tiān', 'day, sky',
'fū', 'husband, man',
'rù', 'to enter',
'cóng', 'from, follow',
'běi', 'north',
'bǐ', 'compare, than',
'míng', 'bright, know',
'zǎo', 'morning, early, long ago',
'bái', 'white, in vain',
'bǎi', 'hundred',
'shí', 'time, hour',
'shì', 'am, is, are, correct',
'shàng', 'upper, go up',
'xià', 'lower, down',
'kǒu', 'mouth',
'gǔ', 'ancient',
'jiào', 'to (be) call(ed)',
'tīng', 'to listen, to hear',
'yán', 'words, say',
'xìn', 'letter, believe',
'shǒu', 'hand',
'yòu', 'again, and',
'shuāng', 'pair, dual, both',
'yǒu', 'friend',
'yǒu', 'to have, there is/are, posses',
'shòu', 'receive, endure, accept',
'ài', 'to love',
'zhēng', 'contend, argue, struggle, fight,',
'fǎn', 'inversive, on the contrary, wrong side out or up / anti-',
'fàn', 'meal, cooked rice',
'qǔ', 'to take, to get, to choose, to fetch',
'zuì', 'most',
'zuǒ', 'left',
'yòu', 'right',
'le / liǎo', 'verb ending / understand, finish, settle',
'zǐ / zi', 'child, son / noun suffix',
'zì', 'character, word',
'gè', '(a measure word), individual',
'zhōng / zhòng', 'center, China / hit',
'cái', 'just, not until, ability',
'mù', 'tree, wood',
'lín', 'woods, forest, Chinese surname',
'běn', 'root, original, book, volume',
'tǐ', 'body / form / style / system',
'shù', 'skill, skill, art',
'lǐ', 'a family name, plum',
'xīu', 'rest, stop',
'guǒ', 'fruit, as expected',
'bù', 'not',
'hái / huán', 'still / return',
'bēi', 'cup, glass',
'tǔ', 'soil, earth, local',
'huài', 'bad, spoiled, broken, to break down',
'zuò', 'to sit',
'gān / gàn', 'have to do with / dry, work',
'yú', 'at, on, in, to, than',
'qiān', 'thousand',
'nǚ', 'female, woman',
'hǎo / hào', 'good, very / like, be fond of',
'rú', 'as (if), like, such as',
'ān', 'safe, secure, install',
'jiā', 'family, home',
'wǒ', 'I, me',
'nǐ', 'you (singular)',
'yě', 'also, too',
'tā', 'he, him, other',
'tā', 'she, her',
'tā', 'it',
'shuǐ', 'water',
'xiǎo', 'small, little (in size)',
'shǎo / shào', 'few, little, less / children, young',
'bàn', 'half',
'gōng', 'work, industry',
'wáng', 'king, Chinese surname',
'zhǔ', 'host, main',
'zhù', 'pour, concentrate',
'zhù', 'to live',
'guó', 'country, state, nation',
'mǎ', 'horse, Chinese surname',
'ma / má/ mǎ', 'a question particle for yes/no questions / what / morphine',
'mā', 'mother, mom',
'fù', 'father',
'bà', 'dad, father',
'ba', 'modal particle indicating polite suggestion, ...right?, ...OK?',
'bǎ', 'hold, take, control, guard, regard as',
'de / dí / dì', '(a possessive particle used after pronoun/noun) / really and truly / aim, target',
'ér', 'child, son',
'jī / jǐ', 'table / several, how many',
'jī', 'machine, chance',
'yàng', 'appearance, sample',
'yǎng', 'raise, provide for',
'měi', 'beautiful',
'Mén', 'door, gate',
'mén', 'particle to plurals form',
'wèn', 'to ask',
'jiān / jiàn', 'room, measure for room / space in between',
'duō', 'many, much, more',
'yè', 'night, evening',
'wàng', 'gaze into the distance',
'shén / shí', 'what / varied',
'me / yào', 'interrogative particle / one',
'jīn', 'now, present',
'zuó', 'yesterday',
'zuò', 'work, do make',
'xīn', 'heart',
'zěn', 'how, why',
'bì', 'certainly, necessary',
'zài', 'exist, in, at, on',
'lái', 'to come',
'qù', 'to go, leave',
'què', 'step back, but, however',
'dào', 'to arrive, reach',
'dǎo / dào', 'to fall, to collapse, to fail, bankrupt / upside down, reverse, pour, tip',
'wén', 'script, literature, written language',
'zhī', 'him, her, it, of',
'zhè', 'this',
'nà', 'that',
'nǎ / na', 'witch, what / particle',
'ne', 'question particle',
'shéi / shuí', 'who, anyone',
'wéi / wèi', 'do, act / for',
'mù', 'eye',
'yǎn', 'eye',
'kān / kàn', 'to read, to see / to look after, take care',
'jiàn', 'to see',
'xiàn', 'appear',
'guān', 'to look at, view',
'dōng', 'east',
'xī', 'west',
'yào', 'to want, important, if',
'nán', 'south',
'huà', 'draw, point, stroke',
'míng', 'name',
'ge', 'each, every',
'wàn', 'ten thousand',
'fāng', 'square',
'fáng', 'house',
'fàng', 'to let off, to let go, to release',
'kě', 'may, but, yet',
'gē', 'elder brother',
'hé', 'river',
'hé', 'why, what, Chinese surname',
'dì', 'younger brother',
'dì', 'ordinal number indicator',
'qiě', 'and, just',
'jiě', 'elder sister',
'mèi', 'younger sister',
'ér', 'and, but',
'yǐ', 'with, according to, and, in order to',
'shān', 'mountain',
'chū', 'to go out, arise, happen, issue, produce',
'huǒ', 'fire',
'diǎn', 'drop a liquid, a little, a bit, light burn',
'zhào', 'shine, reflect, take a picture',
'rè', 'hot, heat',
'rán', 'so, like that, however',
'hēi', 'black',
'shí', 'stone, rock black',
'hé / hè / huo', 'harmonious, and, with / join in the singing, write a poem in reply',
'lì', 'to be sharp, benefit',
'zhǒng / zhòng', 'seed, breed, kind, soft / to plant, to cultivate',
'neì', 'inner, inside',
'tóng', 'same, together',
'shì', 'market, city',
'yòng', 'to use',
'lì', 'strength',
'lì', 'history, go through, calendar',
'nán', 'male, man, son, boy',
'dòng', 'to move',
'dì / de', 'earth / particle',
'mǎi', 'to buy',
'mài', 'to sell',
'duì', 'right, correct, towards, a pair of', 'to sell',
'zhī / zhǐ', 'a measure / only',
'shí', 'to know',
'rèn', 'recognize',
'shēng', 'give birth, unripe, unfamiliar',
'xiān', 'first, ancestor, earlier, in advance',
'hòu', 'back, rear, behind, queen',
'shèng', 'victorious, win, succeed',
'xìng', 'a surname',
'yǔ', 'rain',
'xué', 'to study',
'jué / jiào', 'feel / sleep',
'xí', 'to learn, practice',
'shū', 'book',
'hàn', 'man, Han Chinese',
'jiāng', 'river, Chinese surname',
'yǔ', 'language',
'shuō', 'to say, to speak',
'huà', 'words, dialect, language',
'huó', 'live, alive, living, work',
'jiǎng', 'speak, say, tell',
'jìn', 'to come in, advance',
'dú', 'read, attend, school',
'kū', 'to cry, to weep',
'xiào', 'to smile, to laugh',
'qì', 'utensil, device, tool, utensil, organ',
'péng', 'friend',
'zài', 'again',
'xiàng', 'direction, facing, towards',
'xiǎng', 'sound',
'yīng', 'flower, English, hero',
'fǎ', 'method, way, France',
'chī', 'to eat',
'nián', 'year',
'yuán', 'first, primary, Chinese Dollar',
'yuǎn', 'far',
'jìn', 'near, close',
'máo', 'hair, feather',
'fēn / fèn', 'divide, a unit of weight money / component, part',
'kuài', 'lump, piece, chunk, Chinese Dollar',
'kuài', 'fast, happy, sharp',
'hěn', 'very',
'gēn', 'follow, and',
'zǒu', 'to go, to walk (physically)',
'lù', 'road, way',
'zì', 'self, from',
'jǐ', 'oneself',
'yǐ', 'stop, already',
'gǎi', 'to change, to alter, to transform, to correct',
'qǐ', 'to rise',
'jì', 'to remember, write down',
'méi / mò', 'not have / sink',
'shè', 'to set up, to arrange, to establish, to found, to display',
'yǔ', 'and, together, with',
'xiě', 'to write',
'wǔ', 'noon, midday',
'xǔ', 'to allow, maybe',
'dé / de / děi', 'get, gain / suffix / must',
'dàn', 'but, yet',
'qīng', 'green, young',
'qǐng', 'clear, Qing Dynasty',
'qíng', 'feeling, emotion, passion, situation',
'qǐng', 'please, request, invite',
'jīng', 'refined, perfect, spirit',
'néng', 'can, be able to, ability, energy',
'kāi', 'to open, to start',
'bìng', 'combine, and',
'guān', 'close, turn off, customs house, barriers',
'sòng', 'deliver, give as gift, see sb off',
'chē', 'car, vehicle',
'lián', 'to join, link, even, company military unit',
'jūn', 'army, military, arms',
'cǐ', 'this, these',
'xiē', 'some',
'lǎo', 'old',
'kǎo', 'test, exam',
'zhě', 'person, thing',
'jiāo / jiào', 'teach, instruction / teach, instruction, religion',
'shī', 'teacher',
'zhāo / zhe', 'catch, touch / suffix',
'huì', 'meet, meeting, association, be able to, be likely to',
'liǎng', 'two, both, unit of weight',
'shǐ', 'history',
'shǐ', 'make, cause, envoy, messenger',
'gēng / gèng', 'to change / more, still more',
'biàn / pián', 'than, convenient, informal / cheap',
'jiaō', 'hand in, cross, make friend, mutual',
'xiào / jiào', 'school / proofread, to check, to compare',
'jiào', 'compare, comparatively, quite',
'huí', 'to return, circle, wind',
'hé', 'suit, fit, join, combine, close, shut',
'ná', 'to take, to hold, to get',
'gěi / jǐ', 'give, grant, for, by / supply ,',
'dā / dá', 'to answer, reply',
'zhèng / zhēng', 'upright, straight, correct, principle / Chinese 1st month of year',
'zhēng', 'prove, evidence, certificate, card',
'zhèng', 'politics, government',
'zhěng', 'exactly, whole, entire',
'lì', 'to stand, establish',
'wèi', 'place, location, a polite measure for people',
'yīn', 'sound, noise, news',
'yì', 'mind, meaning, idea',
'zhǎo', 'to look for, give change',
'gōng', 'public, common, male animal, husband father, metric system',
'gòng', 'together, common, Communist Party',
'dǎ / dá', 'hit, strike, play, make / dozen',
'shōu', 'to receive, to accept, income',
'dōu / dū', 'both, all / Chinese surname, metropolis, capital city',
'dāng / dàng', 'work as, ought to, just at / proper, right',
'cháng', 'usually, often, ordinary',
'qì', 'air, gas, make angry',
'qì', 'steam, vapor',
'guò', 'pass, cross, indicating past action',
'chéng', 'finish, complete, accomplish',
'bié', 'leave, part, other, another, don\'t',
'xiàng', 'looks, appearance, each other,',
'xiǎng', 'think, miss, want to',
'sī', 'to think, thought',
'zhì', 'will, aspiration, keep in mind, mark, sign',
'gǎn', 'feel, feeling, be grateful',
'chǎng', 'factory, mill',
'cháng / zhǎng', 'long / grow, leader',
'jiè', 'borrow, lend',
'liàn', 'to practice',
'wǎn', 'evening, night, late',
'qí', 'his, her, it\'s, their, he, she, it, they, that, such',
'qī', 'period of time',
'huà', 'change, convert',
'huā', 'flower, spend, expand',
'huá', 'magnificent, splendid, China, Chinese',
'shì', 'after, thing',
'bǐ', 'pen',
'ràng', 'let, allow, give away',
'yīn', 'cause, because',
'mǔ', 'mother',
'měi', 'each, pair',
'hǎi', 'sea',
'gāo', 'high, tall',
'jīng', 'capital',
'yǐng', 'shadow, photograph',
'diàn', 'electricity, telegram, cable',
'píng', 'flat, even, put down, suppress, calm, peaceful',
'bāo', 'wrap, package',
'yī', 'clothes',
'bèi', 'cover, to wear, quilt, by (in passive voice )',
'zhuāng', 'outfit, clothing, act, dress up, load, pack',
'gù', 'former, old, incident, reason',
'zuò', 'to do, to make',
'fēi', 'to fly',
'tú', 'map, picture',
'yùn', 'carry, transport',
'jiā', 'plus, to add',
'huā / hào', 'howl, yell / name, date, number',
'jiàn', 'letter, document',
'lìng', 'order, command, make, cause',
'lǐng', 'collar, lead, usher',
'lǐ', 'lining, inside, in, Chinese unit of length = 500 meters',
'lǐ', 'reason, logic, natural, science, manage, run',
'qiú', 'beg, seek, strike for',
'qiú', 'sphere, globe, ball',
'xiè', 'thank',
'yóu', 'cause, reason, from',
'zhòng', 'crowd',
'zhī', 'know, realize, knowledge',
'dào', 'direction, road, way, speak, say',
'biān', 'side, boundary, border',
'bìng', 'illness, to get sick',
'cì', 'second-rate, inferior, rate',
'jué', 'decide, determinate',
'lěng', 'cold',
'zhǔn', 'allowed, standard, accurate',
'sǐ', 'die, dead, extremely',
'jiù', 'come near, undertake, accomplish, at once, right away',
'chá', 'tea',
'cài', 'vegetable, dish',
'bào', 'report, newspaper, recompense',
'zhāng', 'open, a measure word for flat objects, Chinese surname',
'chǎn', 'to produce, to give birth',
'chuáng', 'bed',
'huò', 'perhaps, might, possibly, or,',
'máng', 'busy',
'màn', 'slow',
'qián', 'front, former',
'mín', 'the people, civilian',
'shēn', 'body',
'wán', 'intact, whole, finish',
'yuàn', 'yard',
'yuán', 'member, person engaged in something',
'yuán', 'round, circle',
'zhí', 'straight, direct',
'zhēn', 'really, true, real',
'cí', 'word',
'děng', 'wait, class, grade',
'hóng', 'red',
'fēi', 'not, no, wrong',
'kè', 'guest, visitor',
'nán / nàn', 'difficult, unpleasant / disaster',
'shì', 'lifetime, age, era',
'jiè', 'boundary',
'quán', 'whole, complete',
'sè', 'color, scene, women\'s looks, looks, expression',
'wú', 'nothing, not have',
'yì', 'justice, righteousness, meaning',
'qīn', 'parent, relatives, in person',
'xīn', 'new, newly',
'jié', 'festival, economize',
'jiǎo / jué', 'horn / role, part, contend',
'jiě', 'divide, separate, explain, solve',
'shǐ', 'begin, beginning',
'kē', 'branch, division, science',
'jí', 'level, rank',
'jí', 'extremely, pole',
'fēng', 'wind',
'dài', 'generation, dynasty',
'biǎo', 'surface, show, watch',
'bàn', 'do, handle, run, punish',
'dìng', 'calm, stable, decide, subscribe, book',
'gào', 'tell, inform, accuse',
'jì', 'count, compute, idea, plan',
'sù', 'tell, complain, accuse',
'yè', 'line of business, trade, enterprise, cause',
'guāng', 'light, glory, smooth, glossy',
'fù', 'duplicate, answer, recover, resume',
'fú', 'clothes, dress, serve, obey, take, medicine',
'kè', 'overcome, gram',
'kōng / kòng', 'sky, empty, hollow / empty space, free time, vacant, leave empty',
'piàn', 'a flat, thin piece, slice',
'wài', 'outside, outer, outward, other, foreign',
'wàng', 'go, past, toward, to',
'lùn', 'discuss, opinion, view',
'tán', 'talk, chat, what is said',
'xīng', 'star',
'xíng / háng', 'go, travel, OK / line, business, firm',
'xíng', 'form, body',
'xū', 'beard, mustache, must, have to',
'xuǎn', 'select, choose, elect',
'yī', 'doctor, medical service',
'yīng / yìng', 'should / answer, respond',
'gāi', 'should, ought to, this',
'lā', 'to pull, draw',
'niàn', 'think of, study',
'nóng', 'farming, farmer',
'mìng', 'life, order',
'suì', 'year, year of age',
'xīng / xìng', 'become popular / mood, desire',
'xì / jì', 'system, department / tie, fasten',
'tiáo', 'a long narrow piece, item, article, measure word',
'tí', 'to carry, to lift, bring up',
'tí', 'topic, inscribe, write',
'bù', 'to declare, to announce, cloth',
'gòu', 'to declare, to announce, cloth',
'láo', 'work',
'qīng', 'light',
'jīng', 'pass, through, scripture, classics',
'zhòng / chóng', 'heavy, serious / repeat', 'pass, through, scripture, classics',
'liáng / liàng', 'to measure / quantity',
'pǎo', 'to run',
'róng', 'appearance / hold, to contain',
'yì', 'change, easy, simple',
'xū', 'require, to need, to want, necessity',
'jiē', 'to meet, to pick (someone) up, receive',
'hòu', 'wait, time',
'cān / shēn', 'join, take part in, refer, consult / ginseng',
'céng', 'layer',
'dǎo', 'lead',
'bù', 'step, walk',
'dī', 'low',
'bù', 'part, unit, section',
'cuò', 'wrong, mistake, fault',
'fà', 'send, hair',
'bèi', 'prepare, get ready',
'jiē / jié', 'knit, marry / bear, form',
'jǐn', 'tight, urgent',
'miàn', 'face, surface',
'yuán', 'original, primary',
'yuè', 'to exceed, get over',
'zǒng', 'assemble, put together, chief, head, always',
'zǔ', 'organize, group, set, series',
'zhì', 'rule, govern, cure, treat',
'bāng', 'help, gang',
'chǎng', 'open field',
'biàn', 'change',
'jiāng / jiàng', 'be going to, check (in Chinese chess) / general, commander',
'fǔ', 'government office, your home',
'lí', 'to leave, apart',
'lì', 'examples, instances',
'liú', 'to flow, to spread, to circulate, to move',
'shè', 'agency, society, group',
'shén', 'god, spirit',
'shēng', 'sound, voice, tone',
'shì', 'type, pattern, style',
'suī', 'although, even though',
'suàn', 'calculate',
'wù', 'affair, business, must',
'wù', 'thing, object, matter',
'shí', 'real, true, honest, really, solid',
'shāng', 'trade, commerce, discuss, business',
'chá', 'inspect, check',
'àn', 'to press, push down, according to',
'dài', 'belt, type, bring, take',
'shěng / xǐng', 'province, economize, save / examine, be aware',
'suǒ', 'place',
'tè', 'special',
'tōng', 'open, through, understand, know',
'yú', 'fish',
'zhì', 'make, manufacture, system',
'zhǐ', 'finger, point at',
'jiàn', 'build, erect',
'xiàng', 'elephant, imitate',
'shù / shǔ', 'number / count',
'zhǐ', 'paper',
'zhǎn', 'spread out, exhibition',
]
